name: "test"
on:
  workflow_dispatch:

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
          - name: list modules
            run: cat /proc/filesystems

          - name: system-level-dependencies
            run: sudo apt update && sudo apt -y install linux-modules-extra-$(uname -r )  

          - name: list filesystem 
            run: modprobe btrfs && cat /proc/filesystems
