name: "test"
on:
  workflow_dispatch:

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
          - name: list modules
            run: cat /proc/filesystems

  

          - name: Setup tmate session
            uses: mxschmitt/action-tmate@v3
